---
title: "Markov HW 3"
author: "Kathryn Saunders"
date: "2026-02-06"
output: pdf_document
---


```{r setup, include=TRUE}
library(tidyverse) #for graphs and useful functions
library(knitr) #to knit to pdf
library(tinytex) #for LaTeX

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(out.width = "60%",fig.align='center')
```

#Problem 1

d. 
```{r}
#Parameters
a_star <- sqrt(3)-11
c_star <- exp(-a_star) / (3*a_star^2 * (1-a_star))

#Density functions
fx <- function(x) (1/3) * x * (1+x) * exp(-x)
gx <- function(x) c_star * (a_star^2*x*exp(-a_star*x))

#Data frame
x_vals <- seq(0, 10, length.out = 1000)
df <- data.frame(
  x = x_vals,
  target = fx(x_vals),
  proposed = gx(x_vals)
)

#Plot
ggplot(df, aes(x = x)) +
  geom_line(aes(y = target), color="red", size = 1) +
  geom_line(aes(y = proposed), linetype = "dashed", color="blue", size = 1) +
  labs(title = "Acceptance-Rejection Process",
    subtitle = paste("Optimal rate a =", round(a_star, 3),
                     "| c =", round(c_star, 3)),
    caption = "The red line is f(x) and the blue dashed line is c(a*)g(x)",
    x = "x", y = "Density") +
  theme_minimal()

```


#Problem 2

e.
```{r}
#Probability transition matrix
p <- matrix(c(9/10, 1/10, 0,
              0, 7/8, 1/8,
              2/5, 0, 3/5),
            nrow=3, byrow=TRUE)

#Matrix power function
matrix_power <- function(mat, n) {
  result <- diag(nrow(mat))  #identity matrix
  for (i in 1:n) {
    result <- result %*% mat
  }
  return(result)
}

#Calculate p^50
p50 <- matrix_power(p, 50)
p50

```
f.
```{r}
set.seed(987)

#Parameters
states <- c("G", "S", "D")
current_state <- 1  # start in G
n_steps <- 10000
g_time <- 0

for (i in 1:n_steps) {
  if (current_state == 1) {
    g_time <- g_time + 1
  }
  current_state <- sample(1:3, size=1, prob=p[current_state,])
}

time_in_G <- g_time / n_steps
cat("The fraction of time the chain spends in state G is", time_in_G)

```

#Problem 3

c.
```{r}
set.seed(987)

#Probability transition matrix
p2 <- matrix(c(1, 0, 0, 0, 0,
              1/3, 0, 2/3, 0, 0,
              0, 1/3, 0, 2/3, 0,
              0, 0, 1/3, 0, 2/3,
              0, 0, 0, 0, 1),
            nrow=5, byrow=TRUE)

#Matrix power function
matrix_power <- function(mat, n) {
  result <- diag(nrow(mat))  #identity matrix
  for (i in 1:n) {
    result <- result %*% mat
  }
  return(result)
}

#Calculate p^4
p4 <- matrix_power(p2, 4)
p4

p4[2,5]
```
#Problem 4

b.
```{r}
set.seed(987)

##Probability transition matrix
p3 <- matrix(c(1/2, 1/2, 0, 0, 0, 0,
              0, 1/2, 1/2, 0, 0, 0,
              1/3, 0, 1/3, 1/3, 0, 0,
              0, 0, 0, 1/2, 1/2, 0,
              0, 0, 0, 0, 0, 1,
              0, 0, 0, 0, 1, 0), nrow = 6, byrow = TRUE)

#Calculate p^5
p4 <- matrix_power(p3, 5)
p4

p4[1,4]

```

c.
```{r}
set.seed(987)

#Parameters
n_sim <- 10000
steps <- 5
results <- numeric(n_sim)

#Simulation loop
for(i in 1:n_sim) {
  state <- 1
  for(j in 1:steps) {
    state <- sample(1:6, size = 1, prob = p3[state, ])
  }
  results[i] <- state
}

#Results
fraction_4 <- mean(results == 4)
cat("The simulated probability is", fraction_4, ". \n")
cat("The theoretical probability (part b) is 0.1759.")

```



